apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  template:
    metadata:
      name: kafka
      labels:
        app: kafka
    spec:
      containers:
        - name: zookeeper
          image: wurstmeister/zookeeper
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2181
        - name: kafka
          image: wurstmeister/kafka
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: "localhost"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "localhost:2181"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_CREATE_TOPICS
              value: "stream-in:1:1,stream-out:1:1"
        - name: kafka-manager
          image: sheepkiller/kafka-manager
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          env:
            - name: ZK_HOSTS
              value: "localhost:2181"
      restartPolicy: Always
  selector:
    matchLabels:
      app: kafka
